### ISSUE TITLE
Module doesn't work without Vue Router

### ISSUE THREAD

**Issue by owlnai** [nuxt-community/color-mode-module#126]
### Version
@nuxtjs/color-mode: 3.0.0
nuxt: 3.0.0-27418641.56aabd6

### Reproduction Link
[Stackblitz demo](https://stackblitz.com/edit/github-bnnfdx?file=app.vue)
### Steps to reproduce
1 - Create a Nuxt 3 app without a pages/ folder (just app.vue), so Vue Router isn't bundled
2- `npm run dev -o`
3 - Get a `__vite_ssr_import_2__.useRouter is not a function` HTTP 500 error.

Full stacktrace:
```__vite_ssr_import_2__.useRouter is not a function
at eval (file://./.nuxt/dist/server/server.mjs:1789:25)
at callWithNuxt (file://./.nuxt/dist/server/server.mjs:266:20)
at applyPlugin (file://./.nuxt/dist/server/server.mjs:217:29)
at Module.applyPlugins (file://./.nuxt/dist/server/server.mjs:227:11)
at async createNuxtAppServer (file://./.nuxt/dist/server/server.mjs:60:5)
at async renderToString (file://./node_modules/vue-bundle-renderer/dist/index.mjs:257:19)
at async renderMiddleware (file://./.nuxt/nitro/index.mjs:213:20)
at async handle (file://./node_modules/h3/dist/index.mjs:635:19)
```

**Comment by pi0** [comment]
Related: https://github.com/nuxt/framework/pull/3274
