### ISSUE TITLE
Doesn't seem to working with Nuxt 2 + bridge

### ISSUE THREAD

**Issue by Ovab** [nuxt-community/color-mode-module#132]
### Version
@nuxtjs/color-mode: 3.0.2
nuxt: Newest Nuxt 2 bridge

### Steps to reproduce
npm install --save-dev @nuxtjs/color-mode

add "'@nuxtjs/color-mode'" to nuxt config
```
modules: [
    // https://color-mode.nuxtjs.org/
    '@nuxtjs/color-mode',
    // https://bootstrap-vue.org/docs#nuxtjs-module
    'bootstrap-vue/nuxt',
    // https://go.nuxtjs.dev/axios
    '@nuxtjs/axios',
    // https://go.nuxtjs.dev/pwa
    '@nuxtjs/pwa',
    // https://www.npmjs.com/package/cookie-universal-nuxt
    'cookie-universal-nuxt'
  ],

```

### What is Expected?
Code compiles and runs normally, can use plugin following instructions

### What is actually happening?
I get the following build error, this is only happening with the color mode to nuxt config
```
 FATAL  The requested module '@nuxt/kit' does not provide an export named 'addAutoImport'                     12:29:40

  import { defineNuxtModule, createResolver, addTemplate, addPlugin, addComponent, isNuxt2, addAutoImport } from '@nuxt/kit';
  ^^^^^^^^^^^^^
  SyntaxError: The requested module '@nuxt/kit' does not provide an export named 'addAutoImport'
  at ModuleJob._instantiate (node:internal/modules/esm/module_job:124:21)
  at async ModuleJob.run (node:internal/modules/esm/module_job:181:5)
  at async Promise.all (index 0)
  at async ESMLoader.import (node:internal/modules/esm/loader:281:24)
  at async importModuleDynamicallyWrapper (node:internal/vm/module:437:15)
  at async ModuleContainer.addModule (node_modules\@nuxt\core-edge\dist\core.js:174:20)
  at async ModuleContainer.ready (node_modules\@nuxt\core-edge\dist\core.js:47:5)
  at async Nuxt._init (node_modules\@nuxt\core-edge\dist\core.js:346:5)


 ERROR  Cannot start nuxt:  The requested module '@nuxt/kit' does not provide an export named 'addAutoImport' 12:29:40

  import { defineNuxtModule, createResolver, addTemplate, addPlugin, addComponent, isNuxt2, addAutoImport } from '@nuxt/kit';
  ^^^^^^^^^^^^^
  SyntaxError: The requested module '@nuxt/kit' does not provide an export named 'addAutoImport'
  at ModuleJob._instantiate (node:internal/modules/esm/module_job:124:21)
  at async ModuleJob.run (node:internal/modules/esm/module_job:181:5)
  at async Promise.all (index 0)
  at async ESMLoader.import (node:internal/modules/esm/loader:281:24)
  at async importModuleDynamicallyWrapper (node:internal/vm/module:437:15)
  at async ModuleContainer.addModule (node_modules\@nuxt\core-edge\dist\core.js:174:20)
  at async ModuleContainer.ready (node_modules\@nuxt\core-edge\dist\core.js:47:5)
  at async Nuxt._init (node_modules\@nuxt\core-edge\dist\core.js:346:5)
```

**Comment by Atinux** [comment]
Indeed, sadly it's not top priority to support Nuxt bridge since our main focus is on Nuxt 3 right now.

**Comment by Intevel** [comment]
Maybe you can use https://github.com/nuxt-community/color-mode-module/tree/v2.

**Comment by danielroe** [comment]
This should now be fixed in the latest bridge-edge + color mode (3.1.1). Would you check and let me know if not?

**Comment by danielroe** [comment]
@dargmuesli Would you ensure you're using the latest bridge-edge?

**Comment by dargmuesli** [comment]
That indeed fixed the issue. The only thing holding me back to update is https://github.com/nuxt-community/color-mode-module/issues/124 now :partying_face:
