### ISSUE TITLE
When SSR: false, color-mode not working

### ISSUE THREAD

**Issue by franmellanutritienda** [nuxt-community/color-mode-module#143]
### Version
@nuxtjs/color-mode: 3.0.2
nuxt: 3.0.0-rc.2 

### What is actually happening?

Cannot read properties of undefined (reading 'preference')

at http://localhost:3000/_nuxt/node_modules/@nuxtjs/color-mode/dist/runtime/plugin.client.mjs:8:24
at useState (http://localhost:3000/_nuxt/node_modules/nuxt/dist/app/composables/state.mjs:7:26)
at http://localhost:3000/_nuxt/node_modules/@nuxtjs/color-mode/dist/runtime/plugin.client.mjs:7:21
at fn (http://localhost:3000/_nuxt/node_modules/nuxt/dist/app/nuxt.mjs:106:27)
at callWithNuxt (http://localhost:3000/_nuxt/node_modules/nuxt/dist/app/nuxt.mjs:111:12)
at applyPlugin (http://localhost:3000/_nuxt/node_modules/nuxt/dist/app/nuxt.mjs:68:29)
at applyPlugins (http://localhost:3000/_nuxt/node_modules/nuxt/dist/app/nuxt.mjs:77:11)
at async initApp (http://localhost:3000/_nuxt/entry.mjs:44:7)

**Comment by cdowning** [comment]
I am also experiencing this issue.

**Comment by jsegars** [comment]
I believe this is related to a change in Nuxt shortly before the RC where a Nitro hook was removed.  It is mentioned in the PR #139 but there's not any code to fix it yet.
